'------------------------------------------------------------------------------
'  <auto-generated>
'      此代码由编码的 UI 测试生成器生成。
'      版本: 10.0.0.0
'
'      如果重新生成代码，则更改此文件可能会导致错误的行为，
'      并将丢失这些更改。
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.HtmlControls
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace TestProject1
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''RecordedMethod1 - 使用“RecordedMethod1Params”将参数传递到此方法中。
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uIChromeLegacyWindowClient As WinClient = Me.UI日志大厅猎豹安全浏览器Window.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient
            Dim uIChromeLegacyWindowClient1 As WinClient = Me.UI日志大厅猎豹安全浏览器Window.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowClient
            Dim uIChromeLegacyWindowClient2 As WinClient = Me.UI日志大厅猎豹安全浏览器Window.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowClient
            Dim uI创建日志猎豹安全浏览器Document As WinControl = Me.UI日志大厅猎豹安全浏览器Window.UIChromeLegacyWindowWindow2.UI创建日志猎豹安全浏览器Document
            Dim uIChromeLegacyWindowDocument As WinControl = Me.UI日志大厅猎豹安全浏览器Window.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowDocument

            '单击 “Chrome Legacy Window” 客户端
            Mouse.Click(uIChromeLegacyWindowClient, New Point(105, 131))

            '将  使用 右 按钮 “Chrome Legacy Window” 客户端 从(446, 156)移至(711, 304)
            Mouse.StartDragging(uIChromeLegacyWindowClient1, New Point(446, 156), MouseButtons.Right, ModifierKeys.None)
            Mouse.StopDragging(uIChromeLegacyWindowClient1, 265, 148)

            '单击 “Chrome Legacy Window” 客户端
            Mouse.Click(uIChromeLegacyWindowClient, New Point(725, 77))

            '单击 “Chrome Legacy Window” 客户端
            Mouse.Click(uIChromeLegacyWindowClient2, New Point(229, 69))

            '在 “创建日志 - 猎豹安全浏览器” 文档 中键入“test”
            Keyboard.SendKeys(uI创建日志猎豹安全浏览器Document, Me.RecordedMethod1Params.UI创建日志猎豹安全浏览器DocumentSendKeys, ModifierKeys.None)

            '单击 “Chrome Legacy Window” 文档
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(216, 229))

            '在 “创建日志 - 猎豹安全浏览器” 文档 中键入“right”
            Keyboard.SendKeys(uI创建日志猎豹安全浏览器Document, Me.RecordedMethod1Params.UI创建日志猎豹安全浏览器DocumentSendKeys1, ModifierKeys.None)

            '单击 “Chrome Legacy Window” 文档
            Mouse.Click(uIChromeLegacyWindowDocument, New Point(1519, 542))

            '未录制上一个鼠标操作。
        End Sub
        
        '''<summary>
        '''RecordedMethod2
        '''</summary>
        Public Sub RecordedMethod2()
            Dim uI日志大厅选项卡组1TabPage As WinTabPage = Me.UIItem1WindowsInternetWindow.UI选项卡行TabList.UI日志大厅选项卡组1TabPage
            Dim uI我要发表Hyperlink As HtmlHyperlink = Me.UIItem1WindowsInternetWindow.UI日志大厅Document.UI我要发表Hyperlink

            '单击 “日志大厅 选项卡组 1” 选项卡
            Mouse.Click(uI日志大厅选项卡组1TabPage, New Point(100, 15))

            '单击 “我要发表” 链接
            Mouse.Click(uI我要发表Hyperlink, New Point(47, 17))

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。

            '指定的转换无效。
        End Sub
        
        '''<summary>
        '''RecordedMethod3
        '''</summary>
        Public Sub RecordedMethod3()
            Dim uITestHyperlink As HtmlHyperlink = Me.UIItem1WindowsInternetWindow.UI日志大厅Document.UIHeaderPane.UITestHyperlink

            '单击 “test” 链接
            Mouse.Click(uITestHyperlink, New Point(17, 16))
        End Sub
        
        '''<summary>
        '''RecordedMethod4 - 使用“RecordedMethod4Params”将参数传递到此方法中。
        '''</summary>
        Public Sub RecordedMethod4()
            Dim uI龙湖日常分支2Button As WinButton = Me.UI空白页WindowsInternetExWindow.UI收藏夹栏ToolBar.UI龙湖日常分支2Button
            Dim uI运行中的应用程序ToolBar As WinToolBar = Me.UI运行中的应用程序Window.UI运行中的应用程序Client.UI运行中的应用程序ToolBar
            Dim uI锁定任务栏LMenuItem As WinMenuItem = Me.UIItemWindow.UI上下文Menu.UI锁定任务栏LMenuItem
            Dim uITxtUserCodeEdit As HtmlEdit = Me.UI空白页WindowsInternetExWindow.UI龙湖运营管理平台Document.UITxtUserCodeEdit
            Dim uITxtPassWordEdit As HtmlEdit = Me.UI空白页WindowsInternetExWindow.UI龙湖运营管理平台Document.UITxtPassWordEdit
            Dim uI天将雄师Hyperlink As HtmlHyperlink = Me.UI空白页WindowsInternetExWindow.UI毒霸网址大全最安全实用的网址导航Document.UIMainPane.UI天将雄师Hyperlink
            Dim uI付款方式定义Cell As HtmlCell = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UI付款方式定义Cell
            Dim uIItemCell As HtmlCell = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UITrBarRow.UIItemTable.UIItemCell
            Dim uI折扣管理Cell As HtmlCell = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UI折扣管理Cell
            Dim uI销售业务参数设置Cell As HtmlCell = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UI销售业务参数设置Cell

            '单击 “龙湖-日常分支2” 按钮
            Mouse.Click(uI龙湖日常分支2Button, New Point(86, 15))

            '右-单击 “运行中的应用程序” 工具栏
            Mouse.Click(uI运行中的应用程序ToolBar, MouseButtons.Right, ModifierKeys.None, New Point(1039, 20))

            '单击 “锁定任务栏(L)” 菜单项
            Mouse.Click(uI锁定任务栏LMenuItem, New Point(41, 12))

            '在 “txtUserCode” 文本框 中键入“admin”
            uITxtUserCodeEdit.Text = Me.RecordedMethod4Params.UITxtUserCodeEditText

            '在 “txtUserCode” 文本框 中键入“{Enter}”
            Keyboard.SendKeys(uITxtUserCodeEdit, Me.RecordedMethod4Params.UITxtUserCodeEditSendKeys, ModifierKeys.None)

            '在 “txtPassWord” 文本框 中键入“{Enter}”
            Keyboard.SendKeys(uITxtPassWordEdit, Me.RecordedMethod4Params.UITxtPassWordEditSendKeys, ModifierKeys.None)

            '设置标志，以便在非必需操作失败时允许继续播放。(例如，鼠标悬停操作失败时。)
            Playback.PlaybackSettings.ContinueOnError = true

            '鼠标通过  将 “天将雄师” 链接 悬停在 (42, 18) 处
            Mouse.Hover(uI天将雄师Hyperlink, New Point(42, 18))

            '鼠标通过  将 “付款方式定义” 单元格 悬停在 (20, 27) 处
            Mouse.Hover(uI付款方式定义Cell, New Point(20, 27))

            '鼠标通过  将 “名称未知” 单元格 悬停在 (4, 13) 处
            Mouse.Hover(uIItemCell, New Point(4, 13))

            '鼠标通过  将 “折扣管理” 单元格 悬停在 (21, 10) 处
            Mouse.Hover(uI折扣管理Cell, New Point(21, 10))

            '重置标志，以确保在出错时播放停止。
            Playback.PlaybackSettings.ContinueOnError = false

            '单击 “销售业务参数设置” 单元格
            Mouse.Click(uI销售业务参数设置Cell, New Point(47, 12))
        End Sub
        
        '''<summary>
        '''RecordedMethod5 - 使用“RecordedMethod5Params”将参数传递到此方法中。
        '''</summary>
        Public Sub RecordedMethod5()
            Dim uI龙湖日常分支2Button As WinButton = Me.UI空白页WindowsInternetExWindow.UI收藏夹栏ToolBar.UI龙湖日常分支2Button
            Dim uITxtUserCodeEdit As HtmlEdit = Me.UI空白页WindowsInternetExWindow.UI龙湖运营管理平台Document.UITxtUserCodeEdit
            Dim uITxtPassWordEdit As HtmlEdit = Me.UI空白页WindowsInternetExWindow.UI龙湖运营管理平台Document.UITxtPassWordEdit
            Dim uI销售业务参数设置Cell As HtmlCell = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UI销售业务参数设置Cell
            Dim uIItemTable As HtmlTable = Me.UI龙湖运营管理平台CRMWindowsInWindow.UINavFrame.UIFuncNavDocument.UITdmkCell.UIItemTable
            Dim uI折扣管理参数设置Pane As HtmlDiv = Me.UI龙湖运营管理平台CRMWindowsInWindow.UIStageFrame.UIHttp105104768003PubPDocument.UIParamTargetPane.UI折扣管理参数设置Pane

            '单击 “龙湖-日常分支2” 按钮
            Mouse.Click(uI龙湖日常分支2Button, New Point(77, 7))

            '在 “txtUserCode” 文本框 中键入“admin”
            uITxtUserCodeEdit.Text = Me.RecordedMethod5Params.UITxtUserCodeEditText

            '在 “txtUserCode” 文本框 中键入“{Enter}”
            Keyboard.SendKeys(uITxtUserCodeEdit, Me.RecordedMethod5Params.UITxtUserCodeEditSendKeys, ModifierKeys.None)

            '在 “txtPassWord” 文本框 中键入“{Enter}”
            Keyboard.SendKeys(uITxtPassWordEdit, Me.RecordedMethod5Params.UITxtPassWordEditSendKeys, ModifierKeys.None)

            '单击 “销售业务参数设置” 单元格
            Mouse.Click(uI销售业务参数设置Cell, New Point(75, 14))

            '设置标志，以便在非必需操作失败时允许继续播放。(例如，鼠标悬停操作失败时。)
            'Playback.PlaybackSettings.ContinueOnError = true

            '鼠标通过  将 “名称未知” 表 悬停在 (147, 308) 处
            'Mouse.Hover(uIItemTable, New Point(147, 308))

            '重置标志，以确保在出错时播放停止。
            'Playback.PlaybackSettings.ContinueOnError = false

            '单击 “折扣管理参数设置” 窗格
            Mouse.Click(uI折扣管理参数设置Pane, New Point(65, 8))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property RecordedMethod1Params() As RecordedMethod1Params
            Get
                If (Me.mRecordedMethod1Params Is Nothing) Then
                    Me.mRecordedMethod1Params = New RecordedMethod1Params()
                End If
                Return Me.mRecordedMethod1Params
            End Get
        End Property
        
        Public Overridable ReadOnly Property RecordedMethod4Params() As RecordedMethod4Params
            Get
                If (Me.mRecordedMethod4Params Is Nothing) Then
                    Me.mRecordedMethod4Params = New RecordedMethod4Params()
                End If
                Return Me.mRecordedMethod4Params
            End Get
        End Property
        
        Public Overridable ReadOnly Property RecordedMethod5Params() As RecordedMethod5Params
            Get
                If (Me.mRecordedMethod5Params Is Nothing) Then
                    Me.mRecordedMethod5Params = New RecordedMethod5Params()
                End If
                Return Me.mRecordedMethod5Params
            End Get
        End Property
        
        Public ReadOnly Property UI日志大厅猎豹安全浏览器Window() As UI日志大厅猎豹安全浏览器Window
            Get
                If (Me.mUI日志大厅猎豹安全浏览器Window Is Nothing) Then
                    Me.mUI日志大厅猎豹安全浏览器Window = New UI日志大厅猎豹安全浏览器Window()
                End If
                Return Me.mUI日志大厅猎豹安全浏览器Window
            End Get
        End Property
        
        Public ReadOnly Property UIItem1WindowsInternetWindow() As UIItem1WindowsInternetWindow
            Get
                If (Me.mUIItem1WindowsInternetWindow Is Nothing) Then
                    Me.mUIItem1WindowsInternetWindow = New UIItem1WindowsInternetWindow()
                End If
                Return Me.mUIItem1WindowsInternetWindow
            End Get
        End Property
        
        Public ReadOnly Property UI空白页WindowsInternetExWindow() As UI空白页WindowsInternetExWindow
            Get
                If (Me.mUI空白页WindowsInternetExWindow Is Nothing) Then
                    Me.mUI空白页WindowsInternetExWindow = New UI空白页WindowsInternetExWindow()
                End If
                Return Me.mUI空白页WindowsInternetExWindow
            End Get
        End Property
        
        Public ReadOnly Property UI运行中的应用程序Window() As UI运行中的应用程序Window
            Get
                If (Me.mUI运行中的应用程序Window Is Nothing) Then
                    Me.mUI运行中的应用程序Window = New UI运行中的应用程序Window()
                End If
                Return Me.mUI运行中的应用程序Window
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow()
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UI龙湖运营管理平台CRMWindowsInWindow() As UI龙湖运营管理平台CRMWindowsInWindow
            Get
                If (Me.mUI龙湖运营管理平台CRMWindowsInWindow Is Nothing) Then
                    Me.mUI龙湖运营管理平台CRMWindowsInWindow = New UI龙湖运营管理平台CRMWindowsInWindow()
                End If
                Return Me.mUI龙湖运营管理平台CRMWindowsInWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mRecordedMethod1Params As RecordedMethod1Params
        
        Private mRecordedMethod4Params As RecordedMethod4Params
        
        Private mRecordedMethod5Params As RecordedMethod5Params
        
        Private mUI日志大厅猎豹安全浏览器Window As UI日志大厅猎豹安全浏览器Window
        
        Private mUIItem1WindowsInternetWindow As UIItem1WindowsInternetWindow
        
        Private mUI空白页WindowsInternetExWindow As UI空白页WindowsInternetExWindow
        
        Private mUI运行中的应用程序Window As UI运行中的应用程序Window
        
        Private mUIItemWindow As UIItemWindow
        
        Private mUI龙湖运营管理平台CRMWindowsInWindow As UI龙湖运营管理平台CRMWindowsInWindow
        #End Region
    End Class
    
    '''<summary>
    '''要传递到“RecordedMethod1”中的参数
    '''</summary>
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class RecordedMethod1Params
        
        #Region "Fields"
        '''<summary>
        '''在 “创建日志 - 猎豹安全浏览器” 文档 中键入“test”
        '''</summary>
        Public UI创建日志猎豹安全浏览器DocumentSendKeys As String = "test"
        
        '''<summary>
        '''在 “创建日志 - 猎豹安全浏览器” 文档 中键入“right”
        '''</summary>
        Public UI创建日志猎豹安全浏览器DocumentSendKeys1 As String = "right"
        #End Region
    End Class
    
    '''<summary>
    '''要传递到“RecordedMethod4”中的参数
    '''</summary>
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class RecordedMethod4Params
        
        #Region "Fields"
        '''<summary>
        '''在 “txtUserCode” 文本框 中键入“admin”
        '''</summary>
        Public UITxtUserCodeEditText As String = "admin"
        
        '''<summary>
        '''在 “txtUserCode” 文本框 中键入“{Enter}”
        '''</summary>
        Public UITxtUserCodeEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''在 “txtPassWord” 文本框 中键入“{Enter}”
        '''</summary>
        Public UITxtPassWordEditSendKeys As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''要传递到“RecordedMethod5”中的参数
    '''</summary>
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class RecordedMethod5Params
        
        #Region "Fields"
        '''<summary>
        '''在 “txtUserCode” 文本框 中键入“admin”
        '''</summary>
        Public UITxtUserCodeEditText As String = "admin"
        
        '''<summary>
        '''在 “txtUserCode” 文本框 中键入“{Enter}”
        '''</summary>
        Public UITxtUserCodeEditSendKeys As String = "{Enter}"
        
        '''<summary>
        '''在 “txtPassWord” 文本框 中键入“{Enter}”
        '''</summary>
        Public UITxtPassWordEditSendKeys As String = "{Enter}"
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI日志大厅猎豹安全浏览器Window
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "日志大厅 - 猎豹安全浏览器"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Chrome_WidgetWin_100"
            Me.WindowTitles.Add("日志大厅 - 猎豹安全浏览器")
            Me.WindowTitles.Add("testforl - 猎豹安全浏览器")
            Me.WindowTitles.Add("创建日志 - 猎豹安全浏览器")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowWindow() As UIChromeLegacyWindowWindow
            Get
                If (Me.mUIChromeLegacyWindowWindow Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow = New UIChromeLegacyWindowWindow(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowWindow1() As UIChromeLegacyWindowWindow1
            Get
                If (Me.mUIChromeLegacyWindowWindow1 Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow1 = New UIChromeLegacyWindowWindow1(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow1
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowWindow2() As UIChromeLegacyWindowWindow2
            Get
                If (Me.mUIChromeLegacyWindowWindow2 Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow2 = New UIChromeLegacyWindowWindow2(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow2
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowWindow As UIChromeLegacyWindowWindow
        
        Private mUIChromeLegacyWindowWindow1 As UIChromeLegacyWindowWindow1
        
        Private mUIChromeLegacyWindowWindow2 As UIChromeLegacyWindowWindow2
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIChromeLegacyWindowWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "279197632"
            Me.WindowTitles.Add("日志大厅 - 猎豹安全浏览器")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchProperties(WinControl.PropertyNames.Name) = "Chrome Legacy Window"
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("日志大厅 - 猎豹安全浏览器")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIChromeLegacyWindowWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "249561920"
            Me.WindowTitles.Add("testforl - 猎豹安全浏览器")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchProperties(WinControl.PropertyNames.Name) = "Chrome Legacy Window"
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("testforl - 猎豹安全浏览器")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIChromeLegacyWindowWindow2
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "215501248"
            Me.WindowTitles.Add("创建日志 - 猎豹安全浏览器")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchProperties(WinControl.PropertyNames.Name) = "Chrome Legacy Window"
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("创建日志 - 猎豹安全浏览器")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        
        Public ReadOnly Property UI创建日志猎豹安全浏览器Document() As WinControl
            Get
                If (Me.mUI创建日志猎豹安全浏览器Document Is Nothing) Then
                    Me.mUI创建日志猎豹安全浏览器Document = New WinControl(Me)
                    Me.mUI创建日志猎豹安全浏览器Document.SearchProperties(UITestControl.PropertyNames.ControlType) = "Document"
                    Me.mUI创建日志猎豹安全浏览器Document.WindowTitles.Add("创建日志 - 猎豹安全浏览器")
                End If
                Return Me.mUI创建日志猎豹安全浏览器Document
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowDocument() As WinControl
            Get
                If (Me.mUIChromeLegacyWindowDocument Is Nothing) Then
                    Me.mUIChromeLegacyWindowDocument = New WinControl(Me)
                    Me.mUIChromeLegacyWindowDocument.SearchProperties(UITestControl.PropertyNames.ControlType) = "Document"
                    Me.mUIChromeLegacyWindowDocument.WindowTitles.Add("创建日志 - 猎豹安全浏览器")
                End If
                Return Me.mUIChromeLegacyWindowDocument
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowClient As WinClient
        
        Private mUI创建日志猎豹安全浏览器Document As WinControl
        
        Private mUIChromeLegacyWindowDocument As WinControl
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIItem1WindowsInternetWindow
        Inherits BrowserWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(UITestControl.PropertyNames.Name) = "1"
            Me.SearchProperties(UITestControl.PropertyNames.ClassName) = "IEFrame"
            Me.WindowTitles.Add("1")
            Me.WindowTitles.Add("日志大厅")
        End Sub
        
        Public Sub LaunchUrl(ByVal url As System.Uri)
            Me.CopyFrom(BrowserWindow.Launch(url))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI选项卡行TabList() As UI选项卡行TabList
            Get
                If (Me.mUI选项卡行TabList Is Nothing) Then
                    Me.mUI选项卡行TabList = New UI选项卡行TabList(Me)
                End If
                Return Me.mUI选项卡行TabList
            End Get
        End Property
        
        Public ReadOnly Property UI日志大厅Document() As UI日志大厅Document
            Get
                If (Me.mUI日志大厅Document Is Nothing) Then
                    Me.mUI日志大厅Document = New UI日志大厅Document(Me)
                End If
                Return Me.mUI日志大厅Document
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI选项卡行TabList As UI选项卡行TabList
        
        Private mUI日志大厅Document As UI日志大厅Document
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI选项卡行TabList
        Inherits WinTabList
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinTabList.PropertyNames.Name) = "选项卡行"
            Me.WindowTitles.Add("1")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI日志大厅选项卡组1TabPage() As WinTabPage
            Get
                If (Me.mUI日志大厅选项卡组1TabPage Is Nothing) Then
                    Me.mUI日志大厅选项卡组1TabPage = New WinTabPage(Me)
                    Me.mUI日志大厅选项卡组1TabPage.SearchProperties(WinTabPage.PropertyNames.Name) = "日志大厅 选项卡组 1"
                    Me.mUI日志大厅选项卡组1TabPage.WindowTitles.Add("1")
                End If
                Return Me.mUI日志大厅选项卡组1TabPage
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI日志大厅选项卡组1TabPage As WinTabPage
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI日志大厅Document
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "日志大厅"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://10.5.104.76:8006/"
            Me.WindowTitles.Add("日志大厅")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI我要发表Hyperlink() As HtmlHyperlink
            Get
                If (Me.mUI我要发表Hyperlink Is Nothing) Then
                    Me.mUI我要发表Hyperlink = New HtmlHyperlink(Me)
                    Me.mUI我要发表Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Id) = "btnPostNew"
                    Me.mUI我要发表Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Name) = Nothing
                    Me.mUI我要发表Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Target) = "_blank"
                    Me.mUI我要发表Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.InnerText) = "我要发表"
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.AbsolutePath) = "/Article/Create"
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Title) = Nothing
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Href) = "http://10.5.104.76:8006/Article/Create"
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Class) = "btn btn-default"
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.ControlDefinition) = "id=btnPostNew class=""btn btn-default"" st"
                    Me.mUI我要发表Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.TagInstance) = "3"
                    Me.mUI我要发表Hyperlink.WindowTitles.Add("日志大厅")
                End If
                Return Me.mUI我要发表Hyperlink
            End Get
        End Property
        
        Public ReadOnly Property UIHeaderPane() As UIHeaderPane
            Get
                If (Me.mUIHeaderPane Is Nothing) Then
                    Me.mUIHeaderPane = New UIHeaderPane(Me)
                End If
                Return Me.mUIHeaderPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI我要发表Hyperlink As HtmlHyperlink
        
        Private mUIHeaderPane As UIHeaderPane
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIHeaderPane
        Inherits HtmlDiv
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDiv.PropertyNames.Id) = "header"
            Me.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "日志大厅"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" [登陆]"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" 推荐榜我要发表 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1 [2015-03-30 09"
            Me.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=header style=""HEIGHT: 96%; PADDING-TO"
            Me.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "1"
            Me.WindowTitles.Add("日志大厅")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITestHyperlink() As HtmlHyperlink
            Get
                If (Me.mUITestHyperlink Is Nothing) Then
                    Me.mUITestHyperlink = New HtmlHyperlink(Me)
                    Me.mUITestHyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Id) = Nothing
                    Me.mUITestHyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Name) = Nothing
                    Me.mUITestHyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Target) = "_blank"
                    Me.mUITestHyperlink.SearchProperties(HtmlHyperlink.PropertyNames.InnerText) = "test "
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.AbsolutePath) = "/Article/Article/2"
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Title) = Nothing
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Href) = "http://10.5.104.76:8006/Article/Article/2"
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Class) = "btn-success"
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.ControlDefinition) = "class=btn-success href=""/Article/Article"
                    Me.mUITestHyperlink.FilterProperties(HtmlHyperlink.PropertyNames.TagInstance) = "7"
                    Me.mUITestHyperlink.WindowTitles.Add("日志大厅")
                End If
                Return Me.mUITestHyperlink
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITestHyperlink As HtmlHyperlink
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI空白页WindowsInternetExWindow
        Inherits BrowserWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(UITestControl.PropertyNames.Name) = "空白页"
            Me.SearchProperties(UITestControl.PropertyNames.ClassName) = "IEFrame"
            Me.WindowTitles.Add("空白页")
            Me.WindowTitles.Add("龙湖运营管理平台")
            Me.WindowTitles.Add("毒霸网址大全 - 最安全实用的网址导航")
        End Sub
        
        Public Sub LaunchUrl(ByVal url As System.Uri)
            Me.CopyFrom(BrowserWindow.Launch(url))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI收藏夹栏ToolBar() As UI收藏夹栏ToolBar
            Get
                If (Me.mUI收藏夹栏ToolBar Is Nothing) Then
                    Me.mUI收藏夹栏ToolBar = New UI收藏夹栏ToolBar(Me)
                End If
                Return Me.mUI收藏夹栏ToolBar
            End Get
        End Property
        
        Public ReadOnly Property UI龙湖运营管理平台Document() As UI龙湖运营管理平台Document
            Get
                If (Me.mUI龙湖运营管理平台Document Is Nothing) Then
                    Me.mUI龙湖运营管理平台Document = New UI龙湖运营管理平台Document(Me)
                End If
                Return Me.mUI龙湖运营管理平台Document
            End Get
        End Property
        
        Public ReadOnly Property UI毒霸网址大全最安全实用的网址导航Document() As UI毒霸网址大全最安全实用的网址导航Document
            Get
                If (Me.mUI毒霸网址大全最安全实用的网址导航Document Is Nothing) Then
                    Me.mUI毒霸网址大全最安全实用的网址导航Document = New UI毒霸网址大全最安全实用的网址导航Document(Me)
                End If
                Return Me.mUI毒霸网址大全最安全实用的网址导航Document
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI收藏夹栏ToolBar As UI收藏夹栏ToolBar
        
        Private mUI龙湖运营管理平台Document As UI龙湖运营管理平台Document
        
        Private mUI毒霸网址大全最安全实用的网址导航Document As UI毒霸网址大全最安全实用的网址导航Document
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI收藏夹栏ToolBar
        Inherits WinToolBar
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinToolBar.PropertyNames.Name) = "收藏夹栏"
            Me.WindowTitles.Add("空白页")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI龙湖日常分支2Button() As WinButton
            Get
                If (Me.mUI龙湖日常分支2Button Is Nothing) Then
                    Me.mUI龙湖日常分支2Button = New WinButton(Me)
                    Me.mUI龙湖日常分支2Button.SearchProperties(WinButton.PropertyNames.Name) = "龙湖-日常分支2"
                    Me.mUI龙湖日常分支2Button.WindowTitles.Add("空白页")
                End If
                Return Me.mUI龙湖日常分支2Button
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI龙湖日常分支2Button As WinButton
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI龙湖运营管理平台Document
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "龙湖运营管理平台"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://10.5.104.76:8003/"
            Me.WindowTitles.Add("龙湖运营管理平台")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITxtUserCodeEdit() As HtmlEdit
            Get
                If (Me.mUITxtUserCodeEdit Is Nothing) Then
                    Me.mUITxtUserCodeEdit = New HtmlEdit(Me)
                    Me.mUITxtUserCodeEdit.SearchProperties(HtmlEdit.PropertyNames.Id) = "txtUserCode"
                    Me.mUITxtUserCodeEdit.SearchProperties(HtmlEdit.PropertyNames.Name) = "txtUserCode"
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.LabeledBy) = Nothing
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.Type) = "SINGLELINE"
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.Title) = Nothing
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.Class) = Nothing
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.ControlDefinition) = "id=txtUserCode onkeydown=""if(event.keyCo"
                    Me.mUITxtUserCodeEdit.FilterProperties(HtmlEdit.PropertyNames.TagInstance) = "11"
                    Me.mUITxtUserCodeEdit.WindowTitles.Add("龙湖运营管理平台")
                End If
                Return Me.mUITxtUserCodeEdit
            End Get
        End Property
        
        Public ReadOnly Property UITxtPassWordEdit() As HtmlEdit
            Get
                If (Me.mUITxtPassWordEdit Is Nothing) Then
                    Me.mUITxtPassWordEdit = New HtmlEdit(Me)
                    Me.mUITxtPassWordEdit.SearchProperties(HtmlEdit.PropertyNames.Id) = "txtPassWord"
                    Me.mUITxtPassWordEdit.SearchProperties(HtmlEdit.PropertyNames.Name) = "txtPassWord"
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.LabeledBy) = Nothing
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.Type) = "PASSWORD"
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.Title) = Nothing
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.Class) = Nothing
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.ControlDefinition) = "id=txtPassWord onkeydown=""if(event.keyCo"
                    Me.mUITxtPassWordEdit.FilterProperties(HtmlEdit.PropertyNames.TagInstance) = "12"
                    Me.mUITxtPassWordEdit.WindowTitles.Add("龙湖运营管理平台")
                End If
                Return Me.mUITxtPassWordEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITxtUserCodeEdit As HtmlEdit
        
        Private mUITxtPassWordEdit As HtmlEdit
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI毒霸网址大全最安全实用的网址导航Document
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "毒霸网址大全 - 最安全实用的网址导航"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://www.duba.com/?f=ieostart"
            Me.WindowTitles.Add("毒霸网址大全 - 最安全实用的网址导航")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIMainPane() As UIMainPane
            Get
                If (Me.mUIMainPane Is Nothing) Then
                    Me.mUIMainPane = New UIMainPane(Me)
                End If
                Return Me.mUIMainPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIMainPane As UIMainPane
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIMainPane
        Inherits HtmlDiv
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDiv.PropertyNames.Id) = "main"
            Me.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.InnerText) = ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" 武汉[切换] 多云今24 ~ 16℃多云明28 ~ 18℃ 六日天气加载天"
            Me.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=main jQuery17205435539877042461=""129"""
            Me.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "8"
            Me.WindowTitles.Add("毒霸网址大全 - 最安全实用的网址导航")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI天将雄师Hyperlink() As HtmlHyperlink
            Get
                If (Me.mUI天将雄师Hyperlink Is Nothing) Then
                    Me.mUI天将雄师Hyperlink = New HtmlHyperlink(Me)
                    Me.mUI天将雄师Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Id) = Nothing
                    Me.mUI天将雄师Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Name) = Nothing
                    Me.mUI天将雄师Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.Target) = Nothing
                    Me.mUI天将雄师Hyperlink.SearchProperties(HtmlHyperlink.PropertyNames.InnerText) = "天将雄师"
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.AbsolutePath) = "/s/1/1219/2631.html"
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Title) = Nothing
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Href) = "http://ac.wan.liebao.cn/s/1/1219/2631.html?frm=dbdh-kzyy5"
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.Class) = Nothing
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.ControlDefinition) = "href=""http://ac.wan.liebao.cn/s/1/1219/2"
                    Me.mUI天将雄师Hyperlink.FilterProperties(HtmlHyperlink.PropertyNames.TagInstance) = "119"
                    Me.mUI天将雄师Hyperlink.WindowTitles.Add("毒霸网址大全 - 最安全实用的网址导航")
                End If
                Return Me.mUI天将雄师Hyperlink
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI天将雄师Hyperlink As HtmlHyperlink
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI运行中的应用程序Window
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "运行中的应用程序"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "MSTaskSwWClass"
            Me.WindowTitles.Add("运行中的应用程序")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI运行中的应用程序Client() As UI运行中的应用程序Client
            Get
                If (Me.mUI运行中的应用程序Client Is Nothing) Then
                    Me.mUI运行中的应用程序Client = New UI运行中的应用程序Client(Me)
                End If
                Return Me.mUI运行中的应用程序Client
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI运行中的应用程序Client As UI运行中的应用程序Client
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI运行中的应用程序Client
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "运行中的应用程序"
            Me.WindowTitles.Add("运行中的应用程序")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI运行中的应用程序ToolBar() As WinToolBar
            Get
                If (Me.mUI运行中的应用程序ToolBar Is Nothing) Then
                    Me.mUI运行中的应用程序ToolBar = New WinToolBar(Me)
                    Me.mUI运行中的应用程序ToolBar.SearchProperties(WinToolBar.PropertyNames.Name) = "运行中的应用程序"
                    Me.mUI运行中的应用程序ToolBar.WindowTitles.Add("运行中的应用程序")
                End If
                Return Me.mUI运行中的应用程序ToolBar
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI运行中的应用程序ToolBar As WinToolBar
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "上下文"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32768"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI上下文Menu() As UI上下文Menu
            Get
                If (Me.mUI上下文Menu Is Nothing) Then
                    Me.mUI上下文Menu = New UI上下文Menu(Me)
                End If
                Return Me.mUI上下文Menu
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI上下文Menu As UI上下文Menu
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI上下文Menu
        Inherits WinMenu
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenu.PropertyNames.Name) = "上下文"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI锁定任务栏LMenuItem() As WinMenuItem
            Get
                If (Me.mUI锁定任务栏LMenuItem Is Nothing) Then
                    Me.mUI锁定任务栏LMenuItem = New WinMenuItem(Me)
                    Me.mUI锁定任务栏LMenuItem.SearchProperties(WinMenuItem.PropertyNames.Name) = "锁定任务栏(L)"
                End If
                Return Me.mUI锁定任务栏LMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI锁定任务栏LMenuItem As WinMenuItem
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UI龙湖运营管理平台CRMWindowsInWindow
        Inherits BrowserWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(UITestControl.PropertyNames.Name) = "龙湖运营管理平台 – CRM"
            Me.SearchProperties(UITestControl.PropertyNames.ClassName) = "IEFrame"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        Public Sub LaunchUrl(ByVal url As System.Uri)
            Me.CopyFrom(BrowserWindow.Launch(url))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINavFrame() As UINavFrame
            Get
                If (Me.mUINavFrame Is Nothing) Then
                    Me.mUINavFrame = New UINavFrame(Me)
                End If
                Return Me.mUINavFrame
            End Get
        End Property
        
        Public ReadOnly Property UIStageFrame() As UIStageFrame
            Get
                If (Me.mUIStageFrame Is Nothing) Then
                    Me.mUIStageFrame = New UIStageFrame(Me)
                End If
                Return Me.mUIStageFrame
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINavFrame As UINavFrame
        
        Private mUIStageFrame As UIStageFrame
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UINavFrame
        Inherits HtmlFrame
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlFrame.PropertyNames.Id) = "nav1"
            Me.SearchProperties(HtmlFrame.PropertyNames.Name) = "nav"
            Me.FilterProperties(HtmlFrame.PropertyNames.AbsolutePath) = "FuncNav.aspx"
            Me.FilterProperties(HtmlFrame.PropertyNames.PageUrl) = "FuncNav.aspx?FuncCode=&sParam=&ShowCustom="
            Me.FilterProperties(HtmlFrame.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlFrame.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlFrame.PropertyNames.ControlDefinition) = "id=nav1 noResize src=""FuncNav.aspx?FuncC"
            Me.FilterProperties(HtmlFrame.PropertyNames.TagInstance) = "2"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIFuncNavDocument() As UIFuncNavDocument
            Get
                If (Me.mUIFuncNavDocument Is Nothing) Then
                    Me.mUIFuncNavDocument = New UIFuncNavDocument(Me)
                End If
                Return Me.mUIFuncNavDocument
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIFuncNavDocument As UIFuncNavDocument
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIFuncNavDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "True"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "FuncNav"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/FuncNav.aspx"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://10.5.104.76:8003/FuncNav.aspx?FuncCode=&sParam=&ShowCustom="
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI付款方式定义Cell() As HtmlCell
            Get
                If (Me.mUI付款方式定义Cell Is Nothing) Then
                    Me.mUI付款方式定义Cell = New HtmlCell(Me)
                    Me.mUI付款方式定义Cell.SearchProperties(HtmlCell.PropertyNames.Id) = "tdFunc"
                    Me.mUI付款方式定义Cell.SearchProperties(HtmlCell.PropertyNames.Name) = Nothing
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.InnerText) = "付款方式定义"
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.ControlDefinition) = "onclick=selFuncInNav(this) onmouseover='"
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.RowIndex) = "5"
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.ColumnIndex) = "2"
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.Class) = Nothing
                    Me.mUI付款方式定义Cell.FilterProperties(HtmlCell.PropertyNames.TagInstance) = "26"
                    Me.mUI付款方式定义Cell.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUI付款方式定义Cell
            End Get
        End Property
        
        Public ReadOnly Property UITrBarRow() As UITrBarRow
            Get
                If (Me.mUITrBarRow Is Nothing) Then
                    Me.mUITrBarRow = New UITrBarRow(Me)
                End If
                Return Me.mUITrBarRow
            End Get
        End Property
        
        Public ReadOnly Property UI折扣管理Cell() As HtmlCell
            Get
                If (Me.mUI折扣管理Cell Is Nothing) Then
                    Me.mUI折扣管理Cell = New HtmlCell(Me)
                    Me.mUI折扣管理Cell.SearchProperties(HtmlCell.PropertyNames.Id) = "tdFunc"
                    Me.mUI折扣管理Cell.SearchProperties(HtmlCell.PropertyNames.Name) = Nothing
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.InnerText) = "折扣管理"
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.ControlDefinition) = "onclick=selFuncInNav(this) onmouseover='"
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.RowIndex) = "6"
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.ColumnIndex) = "2"
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.Class) = Nothing
                    Me.mUI折扣管理Cell.FilterProperties(HtmlCell.PropertyNames.TagInstance) = "29"
                    Me.mUI折扣管理Cell.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUI折扣管理Cell
            End Get
        End Property
        
        Public ReadOnly Property UI销售业务参数设置Cell() As HtmlCell
            Get
                If (Me.mUI销售业务参数设置Cell Is Nothing) Then
                    Me.mUI销售业务参数设置Cell = New HtmlCell(Me)
                    Me.mUI销售业务参数设置Cell.SearchProperties(HtmlCell.PropertyNames.Id) = "tdFunc"
                    Me.mUI销售业务参数设置Cell.SearchProperties(HtmlCell.PropertyNames.Name) = Nothing
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.InnerText) = "销售业务参数设置"
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.ControlDefinition) = "onclick=selFuncInNav(this) onmouseover='"
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.RowIndex) = "10"
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.ColumnIndex) = "2"
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.Class) = Nothing
                    Me.mUI销售业务参数设置Cell.FilterProperties(HtmlCell.PropertyNames.TagInstance) = "41"
                    Me.mUI销售业务参数设置Cell.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUI销售业务参数设置Cell
            End Get
        End Property
        
        Public ReadOnly Property UITdmkCell() As UITdmkCell
            Get
                If (Me.mUITdmkCell Is Nothing) Then
                    Me.mUITdmkCell = New UITdmkCell(Me)
                End If
                Return Me.mUITdmkCell
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI付款方式定义Cell As HtmlCell
        
        Private mUITrBarRow As UITrBarRow
        
        Private mUI折扣管理Cell As HtmlCell
        
        Private mUI销售业务参数设置Cell As HtmlCell
        
        Private mUITdmkCell As UITdmkCell
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UITrBarRow
        Inherits HtmlRow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlRow.PropertyNames.Id) = "trBar"
            Me.SearchProperties(HtmlRow.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlRow.PropertyNames.InnerText) = ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目户口本"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房源生成"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房间管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"价格管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"付款方式定义"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"折扣管理"&Global.Microsoft.VisualBasic.ChrW(13)
            Me.FilterProperties(HtmlRow.PropertyNames.ControlDefinition) = "id=trBar"
            Me.FilterProperties(HtmlRow.PropertyNames.RowIndex) = "1"
            Me.FilterProperties(HtmlRow.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlRow.PropertyNames.TagInstance) = "6"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemTable() As UIItemTable
            Get
                If (Me.mUIItemTable Is Nothing) Then
                    Me.mUIItemTable = New UIItemTable(Me)
                End If
                Return Me.mUIItemTable
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemTable As UIItemTable
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIItemTable
        Inherits HtmlTable
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlTable.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlTable.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlTable.PropertyNames.InnerText) = ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目户口本"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房源生成"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房间管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"价格管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"付款方式定义"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"折扣管理"&Global.Microsoft.VisualBasic.ChrW(13)
            Me.FilterProperties(HtmlTable.PropertyNames.ControlDefinition) = "style=""FONT-SIZE: 9pt"" cellSpacing=0 cel"
            Me.FilterProperties(HtmlTable.PropertyNames.RowCount) = "11"
            Me.FilterProperties(HtmlTable.PropertyNames.ColumnCount) = "3"
            Me.FilterProperties(HtmlTable.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlTable.PropertyNames.TagInstance) = "1"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemCell() As HtmlCell
            Get
                If (Me.mUIItemCell Is Nothing) Then
                    Me.mUIItemCell = New HtmlCell(Me)
                    Me.mUIItemCell.SearchProperties(HtmlCell.PropertyNames.Id) = Nothing
                    Me.mUIItemCell.SearchProperties(HtmlCell.PropertyNames.Name) = Nothing
                    Me.mUIItemCell.SearchProperties(HtmlCell.PropertyNames.MaxDepth) = "3"
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.InnerText) = Nothing
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.ControlDefinition) = Nothing
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.RowIndex) = "6"
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.ColumnIndex) = "1"
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.Class) = Nothing
                    Me.mUIItemCell.FilterProperties(HtmlCell.PropertyNames.TagInstance) = "20"
                    Me.mUIItemCell.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUIItemCell
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemCell As HtmlCell
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UITdmkCell
        Inherits HtmlCell
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlCell.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlCell.PropertyNames.Name) = "tdmk"
            Me.FilterProperties(HtmlCell.PropertyNames.InnerText) = "销售管理z"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目准备"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目户口本"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房源生成"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房间管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"价格管理"
            Me.FilterProperties(HtmlCell.PropertyNames.ControlDefinition) = "height=""100%"" vAlign=top width=""100%"" na"
            Me.FilterProperties(HtmlCell.PropertyNames.RowIndex) = "0"
            Me.FilterProperties(HtmlCell.PropertyNames.ColumnIndex) = "0"
            Me.FilterProperties(HtmlCell.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlCell.PropertyNames.TagInstance) = "1"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemTable() As HtmlTable
            Get
                If (Me.mUIItemTable Is Nothing) Then
                    Me.mUIItemTable = New HtmlTable(Me)
                    Me.mUIItemTable.SearchProperties(HtmlTable.PropertyNames.Id) = Nothing
                    Me.mUIItemTable.SearchProperties(HtmlTable.PropertyNames.Name) = Nothing
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.InnerText) = "项目准备"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目户口本"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房源生成"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"房间管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"价格管理"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"付款方式定"
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.ControlDefinition) = "style=""BORDER-TOP: #a4a493 1px solid; BO"
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.RowCount) = "2"
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.ColumnCount) = "1"
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.Class) = Nothing
                    Me.mUIItemTable.FilterProperties(HtmlTable.PropertyNames.TagInstance) = "2"
                    Me.mUIItemTable.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUIItemTable
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemTable As HtmlTable
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIStageFrame
        Inherits HtmlFrame
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlFrame.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlFrame.PropertyNames.Name) = "stage"
            Me.FilterProperties(HtmlFrame.PropertyNames.AbsolutePath) = "slxt/xsrz/Index.aspx"
            Me.FilterProperties(HtmlFrame.PropertyNames.PageUrl) = "slxt/xsrz/Index.aspx?Type=Desk?FuncCode="
            Me.FilterProperties(HtmlFrame.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlFrame.PropertyNames.Class) = Nothing
            Me.FilterProperties(HtmlFrame.PropertyNames.ControlDefinition) = "noResize src=""slxt/xsrz/Index.aspx?Type="
            Me.FilterProperties(HtmlFrame.PropertyNames.TagInstance) = "5"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIHttp105104768003PubPDocument() As UIHttp105104768003PubPDocument
            Get
                If (Me.mUIHttp105104768003PubPDocument Is Nothing) Then
                    Me.mUIHttp105104768003PubPDocument = New UIHttp105104768003PubPDocument(Me)
                End If
                Return Me.mUIHttp105104768003PubPDocument
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIHttp105104768003PubPDocument As UIHttp105104768003PubPDocument
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIHttp105104768003PubPDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "True"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/PubProject/BizParam/BizParamSetting.aspx"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://10.5.104.76:8003/PubProject/BizParam/BizParamSetting.aspx?funcid=01010110&"& _ 
                "app=销售业务&Type=XS&"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIParamTargetPane() As UIParamTargetPane
            Get
                If (Me.mUIParamTargetPane Is Nothing) Then
                    Me.mUIParamTargetPane = New UIParamTargetPane(Me)
                End If
                Return Me.mUIParamTargetPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIParamTargetPane As UIParamTargetPane
        #End Region
    End Class
    
    <GeneratedCode("编码的 UI 测试生成器", "10.0.30319.1")>  _
    Public Class UIParamTargetPane
        Inherits HtmlDiv
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDiv.PropertyNames.Id) = "paramTarget"
            Me.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "配置类参数"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"配置类参数设定"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"项目准备"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"产品类型"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"设置产品类型"
            Me.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.Class) = "content"
            Me.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=paramTarget class=content style=""HEIG"
            Me.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "3"
            Me.WindowTitles.Add("龙湖运营管理平台 – CRM")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UI折扣管理参数设置Pane() As HtmlDiv
            Get
                If (Me.mUI折扣管理参数设置Pane Is Nothing) Then
                    Me.mUI折扣管理参数设置Pane = New HtmlDiv(Me)
                    Me.mUI折扣管理参数设置Pane.SearchProperties(HtmlDiv.PropertyNames.Id) = Nothing
                    Me.mUI折扣管理参数设置Pane.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
                    Me.mUI折扣管理参数设置Pane.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "折扣管理参数设置"
                    Me.mUI折扣管理参数设置Pane.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
                    Me.mUI折扣管理参数设置Pane.FilterProperties(HtmlDiv.PropertyNames.Class) = "linktitle"
                    Me.mUI折扣管理参数设置Pane.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "class=linktitle style=""FONT-SIZE: 13px"""
                    Me.mUI折扣管理参数设置Pane.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "25"
                    Me.mUI折扣管理参数设置Pane.WindowTitles.Add("龙湖运营管理平台 – CRM")
                End If
                Return Me.mUI折扣管理参数设置Pane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUI折扣管理参数设置Pane As HtmlDiv
        #End Region
    End Class
End Namespace
